version: '3'

networks:
  xapi_net:

services:
  backend:
    image: xapi-backend-image # 后端项目的Docker镜像名称
    ports:
      - "8090:8090" # 映射后端项目的端口
    depends_on:
      - mysql
      - nacos
      - gateway
    volumes:
      - ./docker-xapi-backend/conf:/app/conf
      - ./docker-xapi-backend/log:/app/log
    extra_hosts:
      - "xpi-gateway.com:192.168.2.104" # 往容器内/etc/hosts文件中添加记录
    environment:
      - DB_HOST=mysql     # 设置后端项目连接的MySQL主机名
      - DB_PORT=3307      # 设置后端项目连接的MySQL端口
      - DB_USER=xapiuser      # 设置后端项目连接的MySQL用户名
      - DB_PASSWORD=xapi123456  # 设置后端项目连接的MySQL密码
      - DB_NAME=xapi      # 设置后端项目连接的MySQL数据库名称
      - NACOS_HOST=nacos  # 设置网关项目连接的Nacos主机名
      - NACOS_PORT=8848   # 设置Nacos的端口
      - GATEWAY_HOST=gateway # 设置后端项目访问网关的主机名
    tty: true
    restart: always
    networks:
      - xapi_net
    # command: ["./scripts/wait-for-nacos.sh", "./xapi-backend"]  #command内应该是可执行文件

  gateway:
    image: xapi-gateway-image # 网关项目的Docker镜像名称
    ports:
      - "8080:8080" # 映射网关项目的端口
    depends_on:
      - nacos
    volumes:
      - ./docker-xapi-gateway/conf:/app/conf
      - ./docker-xapi-gateway/log:/app/log
    environment:
      - NACOS_HOST=nacos # 设置网关项目连接的Nacos主机名
      - NACOS_PORT=8848 # 设置Nacos的端口
    tty: true
    restart: always
    networks:
      - xapi_net

  mysql:
    image: mysql:8.0 # MySQL的Docker镜像名称，你可以根据需要选择版本
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # 设置MySQL的root密码
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=xapi # 创建一个MySQL数据库，并设置其名称
      - MYSQL_USER=xapiuser
      - MYSQL_PASSWORD=xapi123456
    ports:
      - "3307:3306" # 将MySQL的3306端口映射到宿主机的3307端口
    volumes:
      - ./docker-mysql8.0/mysql-data:/var/lib/mysql # 将MySQL数据持久化到宿主机的目录
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 将 ./init.sql 映射到容器内的 /docker-entrypoint-initdb.d/init.sql，这是 MySQL 容器初始化时会自动运行的 SQL 初始化脚本目录。
      # - ./docker-mysql8.0/my.cnf:/etc/mysql/my.cnf  # 将 my.cnf 映射到容器内的 MySQL 配置文件
    tty: true
    restart: always
    networks:
      - xapi_net

  nacos:
    image: nacos/nacos-server:v2.1.2-slim # Nacos的Docker镜像名称
    # container_name: nacos
    restart: always
    volumes:
      - ./docker-nacos2.1.2-slim/logs:/home/nacos/logs
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MODE: standalone
    ports:
      - "8848:8848" # 映射Nacos的端口
    cpu_shares: 4
    mem_limit: 2048M
    networks:
      - xapi_net
